// client/react/src/components/PostOptions/PostOptions.tsx
import React, { memo, useCallback } from 'react';

import { Select, Input, Button } from '../UI/index';

import { SortField, SortOrder } from '../../types';

import './PostOptions.css';

interface PostOptionsProps {
  searchQuery: string;
  onSearchChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  selectedSort: SortField;
  onSortChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  sortOrder: SortOrder;
  onOrderChange: () => void;
}

export const PostOptions: React.FC<PostOptionsProps> = memo(
  ({
    searchQuery,
    onSearchChange,
    selectedSort,
    onSortChange,
    sortOrder,
    onOrderChange,
  }) => {
    const handleSearchChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => onSearchChange(e),
      [onSearchChange]
    );
    const handleSortChange = useCallback(
      (e: React.ChangeEvent<HTMLSelectElement>) => onSortChange(e),
      [onSortChange]
    );
    const handleOrderChange = useCallback(
      () => onOrderChange(),
      [onOrderChange]
    );

    return (
      <div className='post-options'>
        <Input
          label='Поиск по заголовку'
          placeholder='Введите текст...'
          value={searchQuery}
          onChange={handleSearchChange}
        />
        <Select
          label='Сортировать по'
          value={selectedSort}
          onChange={handleSortChange}
          options={[
            { value: 'id', label: 'ID' },
            { value: 'createdAt', label: 'Дата создания' },
            { value: 'updatedAt', label: 'Дата обновления' },
            { value: 'viewsCount', label: 'Просмотры' },
          ]}
        />
        <Button onClick={handleOrderChange}>
          {sortOrder === 'asc' ? 'По убыванию' : 'По возрастанию'}
        </Button>
      </div>
    );
  }
);

// client/angular/src/app/components/post-options/post-options.component.ts
import { ChangeDetectionStrategy } from '@angular/core';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SortField, SortOrder } from '../../types';
import { InputComponent } from '../ui/input/input.component';
import { SelectComponent } from '../ui/select/select.component';
import { ButtonComponent } from '../ui/button/button.component';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'app-post-options',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    InputComponent,
    SelectComponent,
    ButtonComponent,
  ],
  templateUrl: './post-options.component.html',
  styleUrls: ['./post-options.component.css'],
})
export class PostOptionsComponent {
  @Input() searchQuery = '';
  @Output() searchQueryChange = new EventEmitter<string>();
  @Input() selectedSort: SortField = 'id';
  @Output() selectedSortChange = new EventEmitter<SortField>();
  @Input() sortOrder: SortOrder = 'asc';
  @Output() sortOrderChange = new EventEmitter<SortOrder>();

  sortOptions = [
    { value: 'id', label: 'ID' },
    { value: 'createdAt', label: 'Дата создания' },
    { value: 'updatedAt', label: 'Дата обновления' },
    { value: 'viewsCount', label: 'Просмотры' },
  ];

  onSortChange(value: string) {
    this.selectedSortChange.emit(value as SortField);
  }

  toggleSortOrder() {
    const newSortOrder: SortOrder = this.sortOrder === 'asc' ? 'desc' : 'asc';
    this.sortOrder = newSortOrder;
    this.sortOrderChange.emit(newSortOrder);
  }
}

<!-- /client/src/app/components/post-options/post-options.component.html -->
<div class="post-options">
  <app-input
    label="Поиск по заголовку"
    placeholder="Введите текст..."
    [(ngModel)]="searchQuery"
    (ngModelChange)="searchQueryChange.emit($event)"
  ></app-input>
  <app-select
    label="Сортировать по"
    [options]="sortOptions"
    [(ngModel)]="selectedSort"
    (ngModelChange)="onSortChange($any($event).toString())"
  ></app-select>
  <app-button (click)="toggleSortOrder()">
    {{ sortOrder === 'asc' ? 'По убыванию' : 'По возрастанию' }}
  </app-button>
</div>
