// client/react/src/components/PostForm/PostForm.tsx
import React, { memo, useCallback, useState } from 'react';

import { Button, Input } from '../UI/index';

import './PostForm.css';

interface PostFormProps {
  onCreate: (post: {
    title: string;
    text: string;
    imageUrl?: File | null;
  }) => void;
}

export const PostForm: React.FC<PostFormProps> = memo(({ onCreate }) => {
  const [title, setTitle] = useState('');
  const [text, setText] = useState('');
  const [imageUrl, setImageUrl] = useState<File | null>(null);

  const handleSubmit = useCallback(
    (e: React.FormEvent) => {
      e.preventDefault();
      onCreate({ title, text, imageUrl });
      setTitle('');
      setText('');
      setImageUrl(null);
    },
    [title, text, imageUrl, onCreate]
  );

  const handleFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.files && e.target.files[0]) {
        setImageUrl(e.target.files[0]);
      }
    },
    []
  );

  return (
    <form onSubmit={handleSubmit} className='post-form'>
      <Input
        label='Заголовок'
        placeholder='Введите заголовок...'
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        required
      />
      <Input
        label='Текст'
        placeholder='Введите текст...'
        value={text}
        onChange={(e) => setText(e.target.value)}
        required
      />
      <div className='file-input'>
        <input type='file' onChange={handleFileChange} accept='image/*' />
      </div>
      <Button type='submit'>Создать пост</Button>
    </form>
  );
});

// client/angular/src/app/components/post-form/post-form.component.ts
// /client/src/app/components/post-form/post-form.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ButtonComponent } from '../ui/button/button.component';
import { InputComponent } from '../ui/input/input.component';

@Component({
  selector: 'app-post-form',
  standalone: true,
  imports: [CommonModule, FormsModule, ButtonComponent, InputComponent],
  templateUrl: './post-form.component.html',
  styleUrls: ['./post-form.component.css'],
})
export class PostFormComponent {
  @Output() onCreate = new EventEmitter<{
    title: string;
    text: string;
    imageUrl?: File | null;
  }>();
  title = '';
  text = '';
  imageUrl: File | null = null;

  handleSubmit() {
    this.onCreate.emit({
      title: this.title,
      text: this.text,
      imageUrl: this.imageUrl,
    });
    this.title = '';
    this.text = '';
    this.imageUrl = null;
  }

  handleFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files[0]) {
      this.imageUrl = input.files[0];
    }
  }
}

<!-- /client/src/app/components/post-form/post-form.component.html -->
<form (ngSubmit)="handleSubmit()" class="post-form">
  <app-input
    label="Заголовок"
    placeholder="Введите заголовок..."
    [(ngModel)]="title"
    name="title"
    required
  ></app-input>
  <app-input
    label="Текст"
    placeholder="Введите текст..."
    [(ngModel)]="text"
    name="text"
    required
  ></app-input>
  <div class="file-input">
    <input type="file" (change)="handleFileChange($event)" accept="image/*" />
  </div>
  <app-button type="submit">Создать пост</app-button>
</form>
