// client/react/src/pages/PostItemPage/PostItemPage.tsx
import { useState, useEffect } from 'react';
import { useParams } from 'react-router';

import { PostItem } from '../../components';
import { Loader, Modal } from '../../components/UI';

import { PostItemProps } from '../../types';

import apiClient from '../../api/client';

import { useApiCache } from '../../hooks/useApiCache';

import performanceLogger from '../../utils/performanceLogger';

import './PostItemPage.css';

const PostItemPage = () => {
  const [postItem, setPostItem] = useState<PostItemProps | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const { id } = useParams();
  const { fetchData, isLoading, invalidateCache } = useApiCache();

  useEffect(() => {
    if (id) {
      fetchPost();
    }
  }, [id, fetchData]);

  const fetchPost = async () => {
    try {
      const data = await fetchData<PostItemProps>(`/posts/${id}`);
      setPostItem(data);
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };

  const handleUpdatePost = async (formData: FormData) => {
    try {
      const response = await apiClient.patch(`/posts/${id}`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      setPostItem(response.data);
      invalidateCache(`/posts/${id}`); // Инвалидация кэша
      setIsEditing(false);
    } catch (error) {
      console.error('Error updating post:', error);
    }
  };

  const handleDeletePost = async (id: number) => {
    try {
      await apiClient.delete(`/posts/${id}`);
      invalidateCache(`/posts/${id}`); // Инвалидация кэша
    } catch (error) {
      console.error('Error deleting post:', error);
    }
  };

  return (
    <div className='post-item-container'>
      {isLoading ? (
        <Loader text='post-item' />
      ) : (
        <>
          {postItem && (
            <PostItem
              {...postItem}
              onEdit={() => setIsEditing(true)}
              onDelete={handleDeletePost}
            />
          )}
          {isEditing && postItem && (
            <Modal
              post={postItem}
              onUpdate={handleUpdatePost}
              onClose={() => setIsEditing(false)}
            />
          )}
        </>
      )}
    </div>
  );
};

export default PostItemPage;

// client/angular/src/app/pages/post-item-page/post-item-page.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { PostItemProps } from '../../types';
import { ApiClientService } from '../../services/api-client.service';
import { PostItemComponent } from '../../components/post-item/post-item.component';
import { LoaderComponent } from '../../components/ui/loader/loader.component';
import { ModalComponent } from '../../components/ui/modal/modal.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-post-item-page',
  standalone: true,
  imports: [CommonModule, PostItemComponent, LoaderComponent, ModalComponent],
  templateUrl: './post-item-page.component.html',
  styleUrls: ['./post-item-page.component.css'],
})
export class PostItemPageComponent implements OnInit {
  postItem: PostItemProps | null = null;
  isLoading = true;
  isEditing = false;
  id: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private apiClient: ApiClientService,
    private cdr: ChangeDetectorRef // Добавляем ChangeDetectorRef
  ) {}

  ngOnInit() {
    this.id = this.route.snapshot.paramMap.get('id');
    if (this.id) {
      this.apiClient.get<PostItemProps>(`/posts/${this.id}`).subscribe({
        next: (data) => {
          this.postItem = data;
          this.isLoading = false;
          this.cdr.detectChanges(); // Форсируем обновление UI после загрузки
        },
        error: (error) => console.error('Error fetching data:', error),
        complete: () => (this.isLoading = false),
      });
    }
  }

  handleUpdatePost(formData: FormData) {
    this.apiClient
      .patch<PostItemProps>(`/posts/${this.id}`, formData)
      .subscribe({
        next: (data) => {
          this.postItem = { ...data }; // Создаём новый объект для реактивности
          this.isEditing = false;
          this.cdr.detectChanges(); // Форсируем обновление UI
        },
        error: (error) => {
          console.error('Error updating post:', error);
          this.cdr.detectChanges(); // Обновляем UI даже при ошибке
        },
      });
  }

  handleDeletePost(id: number) {
    this.apiClient.delete(`/posts/${id}`).subscribe({
      error: (error) => console.error('Error deleting post:', error),
    });
  }

  onEdit() {
    this.isEditing = true;
    this.cdr.detectChanges(); // Обновляем UI при открытии редактирования
  }
}

<!-- /client/src/app/pages/post-item-page/post-item-page.component.html -->
<div class="post-item-container">
  <app-loader *ngIf="isLoading" text="post-item"></app-loader>
  <ng-container *ngIf="!isLoading && postItem">
    <app-post-item
      [id]="postItem.id"
      [title]="postItem.title"
      [text]="postItem.text"
      [imageUrl]="postItem.imageUrl"
      [createdAt]="postItem.createdAt"
      [updatedAt]="postItem.updatedAt"
      [viewsCount]="postItem.viewsCount"
      (onEdit)="onEdit()"
      (onDelete)="handleDeletePost($event)"
    ></app-post-item>
    <app-modal
      *ngIf="isEditing"
      [post]="postItem"
      (onUpdate)="handleUpdatePost($event)"
      (onClose)="isEditing = false"
    ></app-modal>
  </ng-container>
</div>
