// client/react/src/pages/PostListPage/PostListPage.tsx
import { useState, useEffect } from 'react';
import { PostList, PostOptions, PostForm } from '../../components';
import { Loader, Modal } from '../../components/UI';
import { PostItemProps, SortField, SortOrder } from '../../types';
import apiClient from '../../api/client';
import { usePosts } from '../../hooks/usePosts';
import { useApiCache } from '../../hooks/useApiCache';
import performanceLogger from '../../utils/performanceLogger';
import './PostListPage.css';

const PostListPage = () => {
  const [postList, setPostList] = useState<PostItemProps[]>([]);
  const [selectedSort, setSelectedSort] = useState<SortField>('id');
  const [sortOrder, setSortOrder] = useState<SortOrder>('asc');
  const [searchQuery, setSearchQuery] = useState('');
  const [editingPost, setEditingPost] = useState<PostItemProps | null>(null);
  const { fetchData, isLoading, invalidateCache } = useApiCache();

  useEffect(() => {
    fetchPosts();
  }, [fetchData]);

  const fetchPosts = async () => {
    try {
      const data = await fetchData<PostItemProps[]>('/posts');
      setPostList(data);
    } catch (error) {
      performanceLogger.logError(
        'APIResponseTime',
        error instanceof Error ? error : new Error('Unknown error')
      );
    }
  };

  const handleEditPost = (id: number) => {
    const postToEdit = postList.find((post) => post.id === id);
    if (postToEdit) {
      setEditingPost(postToEdit);
    }
  };

  const handleUpdatePost = async (formData: FormData) => {
    try {
      const response = await apiClient.patch(
        `/posts/${editingPost?.id}`,
        formData,
        { headers: { 'Content-Type': 'multipart/form-data' } }
      );
      setPostList((prev) =>
        prev.map((post) => (post.id === editingPost?.id ? response.data : post))
      );
      invalidateCache('/posts'); // Инвалидация кэша
      setEditingPost(null);
    } catch (error) {
      performanceLogger.logError(
        'APIResponseTime',
        error instanceof Error ? error : new Error('Unknown error')
      );
    }
  };

  const handleCreatePost = async (post: {
    title: string;
    text: string;
    imageUrl?: File | null;
  }) => {
    try {
      const formData = new FormData();
      formData.append('title', post.title);
      formData.append('text', post.text);
      if (post.imageUrl) {
        formData.append('imageUrl', post.imageUrl);
      }
      const response = await apiClient.post('/posts', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      setPostList((prev) => [response.data, ...prev]);
      invalidateCache('/posts'); // Инвалидация кэша
    } catch (error) {
      performanceLogger.logError(
        'APIResponseTime',
        error instanceof Error ? error : new Error('Unknown error')
      );
    }
  };

  const handleDeletePost = async (id: number) => {
    try {
      await apiClient.delete(`/posts/${id}`);
      setPostList((prev) => prev.filter((post) => post.id !== id));
      invalidateCache('/posts'); // Инвалидация кэша
    } catch (error) {
      performanceLogger.logError(
        'APIResponseTime',
        error instanceof Error ? error : new Error('Unknown error')
      );
    }
  };

  const sortedAndSearchedPosts = usePosts(
    postList,
    selectedSort,
    sortOrder,
    searchQuery
  );

  const stopReRender = performanceLogger.start('ReRenderPerformance');
  stopReRender();

  return (
    <div className='post-list-container'>
      {isLoading ? (
        <Loader text='post-list' />
      ) : (
        <>
          <PostForm onCreate={handleCreatePost} />
          <PostOptions
            searchQuery={searchQuery}
            onSearchChange={(e) => setSearchQuery(e.target.value)}
            selectedSort={selectedSort}
            onSortChange={(e) => setSelectedSort(e.target.value as SortField)}
            sortOrder={sortOrder}
            onOrderChange={() =>
              setSortOrder((prev) => (prev === 'asc' ? 'desc' : 'asc'))
            }
          />
          <PostList
            data={sortedAndSearchedPosts}
            onEdit={handleEditPost}
            onDelete={handleDeletePost}
          />
          {editingPost && (
            <Modal
              post={editingPost}
              onUpdate={handleUpdatePost}
              onClose={() => setEditingPost(null)}
            />
          )}
        </>
      )}
    </div>
  );
};

export default PostListPage;

// client/angular/src/app/pages/post-list-page/post-list-page.component.ts
// /client/src/app/pages/post-list-page/post-list-page.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PostItemProps, SortField, SortOrder } from '../../types';
import { ApiClientService } from '../../services/api-client.service';
import { PostFormComponent } from '../../components/post-form/post-form.component';
import { PostOptionsComponent } from '../../components/post-options/post-options.component';
import { PostListComponent } from '../../components/post-list/post-list.component';
import { LoaderComponent } from '../../components/ui/loader/loader.component';
import { ModalComponent } from '../../components/ui/modal/modal.component';
import { SortPostsPipe } from '../../pipes/sort-posts.pipe';
import { HttpHeaders } from '@angular/common/http';

@Component({
  selector: 'app-post-list-page',
  standalone: true,
  imports: [
    CommonModule,
    PostFormComponent,
    PostOptionsComponent,
    PostListComponent,
    LoaderComponent,
    ModalComponent,
    SortPostsPipe,
  ],
  templateUrl: './post-list-page.component.html',
  styleUrls: ['./post-list-page.component.css'],
})
export class PostListPageComponent implements OnInit {
  postList: PostItemProps[] = [];
  isLoading = true;
  selectedSort: SortField = 'id';
  sortOrder: SortOrder = 'asc';
  searchQuery = '';
  editingPost: PostItemProps | null = null;

  constructor(
    private apiClient: ApiClientService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    this.fetchPosts();
  }

  fetchPosts() {
    this.apiClient.get<PostItemProps[]>('/posts').subscribe({
      next: (data) => {
        this.postList = [...data];
        this.isLoading = false;
      },
      error: (error) => console.error('Error fetching data:', error),
      complete: () => (this.isLoading = false),
    });
  }

  handleEditPost(id: number) {
    const postToEdit = this.postList.find((post) => post.id === id);
    if (postToEdit) this.editingPost = postToEdit;
  }

  handleUpdatePost(formData: FormData) {
    this.apiClient
      .patch<PostItemProps>(`/posts/${this.editingPost?.id}`, formData)
      .subscribe({
        next: (data) => {
          this.postList = this.postList.map((post) =>
            post.id === this.editingPost?.id ? data : post
          );
          this.editingPost = null;
          this.cdr.detectChanges();
        },
        error: (error) => {
          console.error('Ошибка при обновлении поста:', error);
        },
      });
  }

  handleCreatePost(post: {
    title: string;
    text: string;
    imageUrl?: File | null;
  }) {
    const formData = new FormData();
    formData.append('title', post.title);
    formData.append('text', post.text);
    if (post.imageUrl) formData.append('imageUrl', post.imageUrl);

    const request = this.apiClient.post<PostItemProps>('/posts', formData);
    request.subscribe({
      next: (data) => {
        console.log('Пост создан:', data);
        this.postList = [data, ...this.postList];
        this.cdr.detectChanges();
      },
      error: (error) => {
        console.error('Ошибка при создании поста:', error);
        console.log('Отправленные заголовки:', error.request?.headers);
      },
    });
  }

  handleDeletePost(id: number) {
    this.apiClient.delete(`/posts/${id}`).subscribe({
      next: () => {
        this.postList = this.postList.filter((post) => post.id !== id);
        this.cdr.detectChanges();
      },
      error: (error) => console.error('Error deleting post:', error),
    });
  }

  handleSearchQueryChange(newQuery: string) {
    this.searchQuery = newQuery;
    this.cdr.detectChanges();
  }

  handleSortChange(newSortField: SortField) {
    this.selectedSort = newSortField;
    this.cdr.detectChanges();
  }

  handleSortOrderChange(newSortOrder: SortOrder) {
    this.sortOrder = newSortOrder;
    this.cdr.detectChanges();
  }
}

<div class="post-list-container">
  <app-post-form (onCreate)="handleCreatePost($event)"></app-post-form>
  <app-post-options
    [searchQuery]="searchQuery"
    [selectedSort]="selectedSort"
    [sortOrder]="sortOrder"
    (searchQueryChange)="handleSearchQueryChange($event)"
    (selectedSortChange)="handleSortChange($event)"
    (sortOrderChange)="handleSortOrderChange($event)"
  ></app-post-options>
  <app-loader *ngIf="isLoading"></app-loader>
  <app-post-list
    *ngIf="!isLoading"
    [data]="postList | sortPosts : selectedSort : sortOrder : searchQuery"
    (onEdit)="handleEditPost($event)"
    (onDelete)="handleDeletePost($event)"
  ></app-post-list>
  <app-modal
    *ngIf="editingPost"
    [post]="editingPost"
    (onUpdate)="handleUpdatePost($event)"
    (onClose)="editingPost = null"
  ></app-modal>
</div>
