// client/react/src/components/PostItem/PostItem.tsx
import React, { memo, useCallback } from 'react';
import { useNavigate } from 'react-router';

import { Button } from '../UI';

import { PostItemProps } from '../../types';

import apiClient from '../../api/client';

import performanceLogger from '../../utils/performanceLogger';

import './PostItem.css';

export const PostItem: React.FC<PostItemProps> = memo(
  ({
    id,
    title,
    text,
    imageUrl,
    createdAt,
    updatedAt,
    viewsCount,
    onEdit,
    onDelete,
  }) => {
    const navigate = useNavigate();

    const handleClick = useCallback(() => {
      const stop = performanceLogger.start('EventHandlingLatency');
      navigate(`/posts/${id}`);
      stop();
    }, [id, navigate]);

    const handleEdit = useCallback(() => {
      const stop = performanceLogger.start('EventHandlingLatency');
      onEdit(id);
      stop();
    }, [id, onEdit]);

    const handleDelete = useCallback(() => {
      const stop = performanceLogger.start('EventHandlingLatency');
      onDelete(id);
      stop();
    }, [id, onDelete]);

    const fullImageUrl = imageUrl
      ? `${apiClient.defaults.baseURL}${imageUrl}`
      : null;

    return (
      <div className='post-item'>
        <h2 onClick={handleClick}>{title}</h2>
        <p>{text}</p>
        {imageUrl && (
          <img
            src={fullImageUrl!}
            alt={title}
            className='post-image'
            onError={(e) => {
              console.error('Error loading image:', imageUrl);
              e.currentTarget.style.display = 'none';
            }}
          />
        )}
        <div className='post-meta'>
          <span>Post ID: {id}</span>
          <br />
          <span>Created at: {new Date(createdAt).toLocaleString()}</span>
          <br />
          <span>Updated at: {new Date(updatedAt).toLocaleString()}</span>
          <br />
          <span>Views count: {viewsCount}</span>
        </div>
        <div className='post-actions'>
          <Button onClick={handleEdit}>Редактировать</Button>
          <Button onClick={handleDelete}>Удалить</Button>
        </div>
      </div>
    );
  }
);

// client/angular/src/app/components/post-item/post-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { ButtonComponent } from '../ui/button/button.component';
import { ApiClientService } from '../../services/api-client.service';
import { PerformanceLoggerService } from '../../services/performance-logger.service';

@Component({
  selector: 'app-post-item',
  standalone: true,
  imports: [CommonModule, ButtonComponent],
  templateUrl: './post-item.component.html',
  styleUrls: ['./post-item.component.css'],
})
export class PostItemComponent {
  @Input() id!: number;
  @Input() title!: string;
  @Input() text!: string;
  @Input() imageUrl?: string;
  @Input() createdAt!: string;
  @Input() updatedAt!: string;
  @Input() viewsCount!: number;
  @Output() onEdit = new EventEmitter<number>();
  @Output() onDelete = new EventEmitter<number>();

  constructor(
    private router: Router,
    private apiClient: ApiClientService,
    private performanceLogger: PerformanceLoggerService
  ) {}

  handleClick() {
    const stop = this.performanceLogger.start('EventHandlingLatency');
    this.router.navigate([`/posts/${this.id}`]);
    stop();
  }

  handleEdit() {
    const stop = this.performanceLogger.start('EventHandlingLatency');
    this.onEdit.emit(this.id);
    stop();
  }

  handleDelete() {
    const stop = this.performanceLogger.start('EventHandlingLatency');
    this.onDelete.emit(this.id);
    stop();
  }

  get fullImageUrl(): string | null {
    return this.imageUrl
      ? `${this.apiClient.getBaseURL()}${this.imageUrl}`
      : null;
  }

  handleImageError(event: Event) {
    console.error('Error loading image:', this.imageUrl);
    (event.target as HTMLImageElement).style.display = 'none';
  }
}

<div class="post-item">
  <h2 (click)="handleClick()">{{ title }}</h2>
  <p>{{ text }}</p>
  <img
    *ngIf="imageUrl"
    [src]="fullImageUrl!"
    [alt]="title"
    class="post-image"
    (error)="handleImageError($event)"
  />
  <div class="post-meta">
    <span>Post ID: {{ id }}</span
    ><br />
    <span>Created at: {{ createdAt | date : 'medium' }}</span
    ><br />
    <span>Updated at: {{ updatedAt | date : 'medium' }}</span
    ><br />
    <span>Views count: {{ viewsCount }}</span>
  </div>
  <div class="post-actions">
    <app-button (click)="handleEdit()">Редактировать</app-button>
    <app-button (click)="handleDelete()">Удалить</app-button>
  </div>
</div>
