// client/vue/src/components/PostItem.vue
<template>
  <div class="post-item">
    <h2 @click="handleClick">{{ title }}</h2>
    <p>{{ text }}</p>
    <img v-if="imageUrl" :src="fullImageUrl" :alt="title" class="post-image" @error="handleImageError" />
    <div class="post-meta">
      <span>Post ID: {{ id }}</span><br />
      <span>Created at: {{ new Date(createdAt).toLocaleString() }}</span><br />
      <span>Updated at: {{ new Date(updatedAt).toLocaleString() }}</span><br />
      <span>Views count: {{ viewsCount }}</span>
    </div>
    <div class="post-actions">
      <Button @click="handleEdit">Редактировать</Button>
      <Button @click="handleDelete">Удалить</Button>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import { Button } from '@/components/UI';
import { apiClient } from '@/api/client';
import performanceLogger from '@/utils/performanceLogger';

const props = defineProps({
  id: Number,
  title: String,
  text: String,
  imageUrl: String,
  createdAt: String,
  updatedAt: String,
  viewsCount: Number,
  onEdit: Function,
  onDelete: Function
});

const router = useRouter();

const fullImageUrl = computed(() =>
  props.imageUrl ? `${apiClient.defaults.baseURL}${props.imageUrl}` : null
);

const handleClick = () => {
  const stop = performanceLogger.start('EventHandlingLatency');
  router.push(`/posts/${props.id}`);
  stop();
};

const handleEdit = () => {
  const stop = performanceLogger.start('EventHandlingLatency');
  props.onEdit(props.id);
  stop();
};

const handleDelete = () => {
  const stop = performanceLogger.start('EventHandlingLatency');
  props.onDelete(props.id);
  stop();
};

const handleImageError = (e) => {
  console.error('Error loading image:', props.imageUrl);
  e.target.style.display = 'none';
};
</script>

<style scoped>
.post-item {
  border: 1px solid #ccc;
  padding: 20px;
  border-radius: 8px;
  background-color: #ffffff;
  margin-bottom: 20px;
}

.post-item h2 {
  cursor: pointer;
}

.post-meta {
  margin-top: 10px;
  font-size: 0.9rem;
  color: #666;
}

.post-actions {
  margin-top: 10px;
  display: flex;
  gap: 10px;
}

.post-image {
  width: 500px;
  height: 400px;
  border-radius: 8px;
}
</style>

// client/react/src/components/PostItem/PostItem.tsx
import React, { memo, useCallback } from 'react';
import { useNavigate } from 'react-router';

import { Button } from '../UI';

import { PostItemProps } from '../../types';

import apiClient from '../../api/client';

import performanceLogger from '../../utils/performanceLogger';

import './PostItem.css';

export const PostItem: React.FC<PostItemProps> = memo(
  ({
    id,
    title,
    text,
    imageUrl,
    createdAt,
    updatedAt,
    viewsCount,
    onEdit,
    onDelete,
  }) => {
    const navigate = useNavigate();

    const handleClick = useCallback(() => {
      const stop = performanceLogger.start('EventHandlingLatency');
      navigate(`/posts/${id}`);
      stop();
    }, [id, navigate]);

    const handleEdit = useCallback(() => {
      const stop = performanceLogger.start('EventHandlingLatency');
      onEdit(id);
      stop();
    }, [id, onEdit]);

    const handleDelete = useCallback(() => {
      const stop = performanceLogger.start('EventHandlingLatency');
      onDelete(id);
      stop();
    }, [id, onDelete]);

    const fullImageUrl = imageUrl
      ? `${apiClient.defaults.baseURL}${imageUrl}`
      : null;

    return (
      <div className='post-item'>
        <h2 onClick={handleClick}>{title}</h2>
        <p>{text}</p>
        {imageUrl && (
          <img
            src={fullImageUrl!}
            alt={title}
            className='post-image'
            onError={(e) => {
              console.error('Error loading image:', imageUrl);
              e.currentTarget.style.display = 'none';
            }}
          />
        )}
        <div className='post-meta'>
          <span>Post ID: {id}</span>
          <br />
          <span>Created at: {new Date(createdAt).toLocaleString()}</span>
          <br />
          <span>Updated at: {new Date(updatedAt).toLocaleString()}</span>
          <br />
          <span>Views count: {viewsCount}</span>
        </div>
        <div className='post-actions'>
          <Button onClick={handleEdit}>Редактировать</Button>
          <Button onClick={handleDelete}>Удалить</Button>
        </div>
      </div>
    );
  }
);
