// client/react/src/components/UI/Modal/Modal.tsx
import React, { memo, useState, useCallback } from 'react';

import { Button, Input } from '../index';

import './Modal.css';

interface ModalProps {
  post: {
    id: number;
    title: string;
    text: string;
    imageUrl?: string;
  };
  onUpdate: (updatedPost: FormData) => void;
  onClose: () => void;
}

export const Modal: React.FC<ModalProps> = memo(
  ({ post, onUpdate, onClose }) => {
    const [title, setTitle] = useState(post.title);
    const [text, setText] = useState(post.text);
    const [imageFile, setImageFile] = useState<File | null>(null);
    const [previewUrl, setPreviewUrl] = useState<string | null>(
      post.imageUrl || null
    );

    const handleSubmit = useCallback(
      (e: React.FormEvent) => {
        e.preventDefault();
        const formData = new FormData();
        formData.append('title', title);
        formData.append('text', text);
        if (imageFile) {
          formData.append('imageUrl', imageFile);
        }
        onUpdate(formData);
        onClose();
      },
      [title, text, imageFile, onUpdate, onClose]
    );

    const handleFileChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
          const file = e.target.files[0];
          setImageFile(file);
          setPreviewUrl(URL.createObjectURL(file));
        }
      },
      []
    );

    const handleClose = useCallback(() => onClose(), [onClose]);

    return (
      <div className='modal-overlay'>
        <div className='modal-content'>
          <h2>Редактировать пост</h2>
          <form onSubmit={handleSubmit}>
            <Input
              label='Заголовок'
              placeholder='Введите заголовок...'
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required
            />
            <Input
              label='Текст'
              placeholder='Введите текст...'
              value={text}
              onChange={(e) => setText(e.target.value)}
              required
            />
            <div className='file-input'>
              <input type='file' onChange={handleFileChange} accept='image/*' />
              {previewUrl && <img src={previewUrl} alt='Preview' />}
            </div>
            <div>
              <Button type='submit'>Сохранить</Button>
              <Button type='button' onClick={handleClose}>
                Отмена
              </Button>
            </div>
          </form>
        </div>
      </div>
    );
  }
);

// client/angular/src/app/components/ui/modal/modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ButtonComponent } from '../button/button.component';
import { InputComponent } from '../input/input.component';

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [CommonModule, FormsModule, ButtonComponent, InputComponent],
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.css'],
})
export class ModalComponent {
  @Input() post!: {
    id: number;
    title: string;
    text: string;
    imageUrl?: string;
  };
  @Output() onUpdate = new EventEmitter<FormData>();
  @Output() onClose = new EventEmitter<void>();

  title = '';
  text = '';
  imageFile: File | null = null;
  previewUrl: string | null = null;

  ngOnInit() {
    this.title = this.post.title;
    this.text = this.post.text;
    this.previewUrl = this.post.imageUrl || null;
  }

  handleSubmit() {
    const formData = new FormData();
    formData.append('title', this.title);
    formData.append('text', this.text);
    if (this.imageFile) {
      formData.append('imageUrl', this.imageFile); // Новое изображение
    } else if (this.post.imageUrl) {
      formData.append('imageUrl', this.post.imageUrl); // Сохраняем старое, если новое не выбрано
    }
    this.onUpdate.emit(formData);
    this.onClose.emit();
  }

  handleFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files[0]) {
      this.imageFile = input.files[0];
      this.previewUrl = URL.createObjectURL(this.imageFile);
    }
  }
}

<!-- /client/src/app/components/ui/modal/modal.component.html -->
<div class="modal-overlay">
  <div class="modal-content">
    <h2>Редактировать пост</h2>
    <form (ngSubmit)="handleSubmit()">
      <app-input
        label="Заголовок"
        placeholder="Введите заголовок..."
        [(ngModel)]="title"
        name="title"
        required
      ></app-input>
      <app-input
        label="Текст"
        placeholder="Введите текст..."
        [(ngModel)]="text"
        name="text"
        required
      ></app-input>
      <div class="file-input">
        <input
          type="file"
          (change)="handleFileChange($event)"
          accept="image/*"
        />
        <img *ngIf="previewUrl" [src]="previewUrl" alt="Preview" />
      </div>
      <div>
        <app-button type="submit">Сохранить</app-button>
        <app-button type="button" (click)="onClose.emit()">Отмена</app-button>
      </div>
    </form>
  </div>
</div>
