// client/vue/src/components/PostOptions.vue
<template>
  <div class="post-options">
    <Input label="Поиск по заголовку" placeholder="Введите текст..." :model-value="searchQuery"
      @update:model-value="$emit('update:searchQuery', $event)" />
    <Select label="Сортировать по" :model-value="selectedSort" @update:model-value="$emit('update:selectedSort', $event)" :options="sortOptions" />
    <Button @click="onOrderChange">
      {{ sortOrder === 'asc' ? 'По убыванию' : 'По возрастанию' }}
    </Button>
  </div>
</template>

<script setup>
import { Input, Button, Select } from '@/components/UI';

defineProps({
  searchQuery: String,
  selectedSort: String,
  sortOrder: String,
  onOrderChange: Function
});

defineEmits(['update:searchQuery', 'update:selectedSort']);

const sortOptions = [
  { value: 'id', label: 'ID' },
  { value: 'createdAt', label: 'Дата создания' },
  { value: 'updatedAt', label: 'Дата обновления' },
  { value: 'viewsCount', label: 'Просмотры' }
];
</script>

<style scoped>
.post-options {
  background-color: #ffffff;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 20px;
}
</style>

// client/react/src/components/PostOptions/PostOptions.tsx
import React, { memo, useCallback } from 'react';

import { Select, Input, Button } from '../UI/index';

import { SortField, SortOrder } from '../../types';

import './PostOptions.css';

interface PostOptionsProps {
  searchQuery: string;
  onSearchChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  selectedSort: SortField;
  onSortChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  sortOrder: SortOrder;
  onOrderChange: () => void;
}

export const PostOptions: React.FC<PostOptionsProps> = memo(
  ({
    searchQuery,
    onSearchChange,
    selectedSort,
    onSortChange,
    sortOrder,
    onOrderChange,
  }) => {
    const handleSearchChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => onSearchChange(e),
      [onSearchChange]
    );
    const handleSortChange = useCallback(
      (e: React.ChangeEvent<HTMLSelectElement>) => onSortChange(e),
      [onSortChange]
    );
    const handleOrderChange = useCallback(
      () => onOrderChange(),
      [onOrderChange]
    );

    return (
      <div className='post-options'>
        <Input
          label='Поиск по заголовку'
          placeholder='Введите текст...'
          value={searchQuery}
          onChange={handleSearchChange}
        />
        <Select
          label='Сортировать по'
          value={selectedSort}
          onChange={handleSortChange}
          options={[
            { value: 'id', label: 'ID' },
            { value: 'createdAt', label: 'Дата создания' },
            { value: 'updatedAt', label: 'Дата обновления' },
            { value: 'viewsCount', label: 'Просмотры' },
          ]}
        />
        <Button onClick={handleOrderChange}>
          {sortOrder === 'asc' ? 'По убыванию' : 'По возрастанию'}
        </Button>
      </div>
    );
  }
);
