// client/vue/src/components/PostForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="post-form">
    <Input label="Заголовок" placeholder="Введите заголовок..." v-model="title" required />
    <Input label="Текст" placeholder="Введите текст..." v-model="text" required />
    <div class="file-input">
      <input type="file" @change="handleFileChange" accept="image/*" />
    </div>
    <Button type="submit">Создать пост</Button>
  </form>
</template>

<script setup>
import { ref } from 'vue';
import { Input, Button } from '@/components/UI';

const props = defineProps({
  onCreate: {
    type: Function,
    required: true
  }
});

const title = ref('');
const text = ref('');
const imageUrl = ref(null);

const handleSubmit = () => {
  props.onCreate({ title: title.value, text: text.value, imageUrl: imageUrl.value });
  title.value = '';
  text.value = '';
  imageUrl.value = null;
};

const handleFileChange = (e) => {
  if (e.target.files && e.target.files[0]) {
    imageUrl.value = e.target.files[0];
  }
};
</script>

<style scoped>
.post-form {
  display: flex;
  flex-direction: column;
  justify-content: center;
  margin-bottom: 20px;
  background-color: #ffffff;
  border-radius: 8px;
  padding: 16px;
}

.post-form .input {
  margin-bottom: 10px;
}

.post-form .file-input {
  margin-bottom: 10px;
}

.post-form .file-input label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.post-form .button {
  margin-top: 10px;
}
</style>

// client/react/src/components/PostForm/PostForm.tsx
import React, { memo, useCallback, useState } from 'react';

import { Button, Input } from '../UI/index';

import './PostForm.css';

interface PostFormProps {
  onCreate: (post: {
    title: string;
    text: string;
    imageUrl?: File | null;
  }) => void;
}

export const PostForm: React.FC<PostFormProps> = memo(({ onCreate }) => {
  const [title, setTitle] = useState('');
  const [text, setText] = useState('');
  const [imageUrl, setImageUrl] = useState<File | null>(null);

  const handleSubmit = useCallback(
    (e: React.FormEvent) => {
      e.preventDefault();
      onCreate({ title, text, imageUrl });
      setTitle('');
      setText('');
      setImageUrl(null);
    },
    [title, text, imageUrl, onCreate]
  );

  const handleFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.files && e.target.files[0]) {
        setImageUrl(e.target.files[0]);
      }
    },
    []
  );

  return (
    <form onSubmit={handleSubmit} className='post-form'>
      <Input
        label='Заголовок'
        placeholder='Введите заголовок...'
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        required
      />
      <Input
        label='Текст'
        placeholder='Введите текст...'
        value={text}
        onChange={(e) => setText(e.target.value)}
        required
      />
      <div className='file-input'>
        <input type='file' onChange={handleFileChange} accept='image/*' />
      </div>
      <Button type='submit'>Создать пост</Button>
    </form>
  );
});
