// client/react/src/pages/PostItemPage/PostItemPage.tsx
import { useState, useEffect } from 'react';
import { useParams } from 'react-router';

import { PostItem } from '../../components';
import { Loader, Modal } from '../../components/UI';

import { PostItemProps } from '../../types';

import apiClient from '../../api/client';

import { useApiCache } from '../../hooks/useApiCache';

import performanceLogger from '../../utils/performanceLogger';

import './PostItemPage.css';

const PostItemPage = () => {
  const [postItem, setPostItem] = useState<PostItemProps | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const { id } = useParams();
  const { fetchData, isLoading, invalidateCache } = useApiCache();

  useEffect(() => {
    if (id) {
      fetchPost();
    }
  }, [id, fetchData]);

  const fetchPost = async () => {
    try {
      const data = await fetchData<PostItemProps>(`/posts/${id}`);
      setPostItem(data);
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };

  const handleUpdatePost = async (formData: FormData) => {
    try {
      const response = await apiClient.patch(`/posts/${id}`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      setPostItem(response.data);
      invalidateCache(`/posts/${id}`); // Инвалидация кэша
      setIsEditing(false);
    } catch (error) {
      console.error('Error updating post:', error);
    }
  };

  const handleDeletePost = async (id: number) => {
    try {
      await apiClient.delete(`/posts/${id}`);
      invalidateCache(`/posts/${id}`); // Инвалидация кэша
    } catch (error) {
      console.error('Error deleting post:', error);
    }
  };

  return (
    <div className='post-item-container'>
      {isLoading ? (
        <Loader text='post-item' />
      ) : (
        <>
          {postItem && (
            <PostItem
              {...postItem}
              onEdit={() => setIsEditing(true)}
              onDelete={handleDeletePost}
            />
          )}
          {isEditing && postItem && (
            <Modal
              post={postItem}
              onUpdate={handleUpdatePost}
              onClose={() => setIsEditing(false)}
            />
          )}
        </>
      )}
    </div>
  );
};

export default PostItemPage;

// client/vue/src/pages/PostItemPage.vue
<template>
  <div class="post-item-container">
    <Loader v-if="isLoading" text="post-item" />
    <template v-else>
      <PostItem v-if="postItem" v-bind="postItem" :on-edit="() => isEditing = true" :on-delete="handleDeletePost" />
      <Modal v-if="isEditing && postItem" :post="postItem" :on-update="handleUpdatePost"
        :on-close="() => isEditing = false" />
    </template>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { useRoute } from 'vue-router';
import { PostItem } from '@/components';
import { Loader, Modal } from '@/components/UI';
import { apiClient } from '@/api/client';

const route = useRoute();
const postItem = ref(null);
const isLoading = ref(true);
const isEditing = ref(false);

onMounted(async () => {
  try {
    const response = await apiClient.get(`/posts/${route.params.id}`);
    postItem.value = response.data;
  } catch (error) {
    console.error('Error fetching data:', error);
  } finally {
    isLoading.value = false;
  }
});

const handleUpdatePost = async (formData) => {
  try {
    const response = await apiClient.patch(`/posts/${route.params.id}`, formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    postItem.value = response.data;
    isEditing.value = false;
  } catch (error) {
    console.error('Error updating post:', error);
  }
};

const handleDeletePost = async (id) => {
  try {
    await apiClient.delete(`/posts/${id}`);
  } catch (error) {
    console.error('Error deleting post:', error);
  }
};
</script>

<style scoped>
.post-item-container {
  margin: 0 auto;
  max-width: 800px;
  padding: 20px;
}
</style>
